10 PRINT "THIS PROGRAM WILL CALCULATE THE VOLUME OF A SPHERE IN CUBIC METERS"
20 PRINT "ENTER THE RADIUS AND THE COMPUTER WILL CALCULATE THE VOLUME"
30 INPUT R
40 V=(4/3)*PI*(R^3)
50 PRINT "VOLUME (CUBIC METERS): ";V